/**
 * Shared image buffer resolver for enhancement providers.
 *
 * Handles three source types:
 *   1. /api/media/[id]  — reads the binary directly from PostgreSQL MediaUpload,
 *      bypassing HTTP entirely. This avoids the "Failed to parse URL" error that
 *      occurs when server-side fetch() receives a relative path.
 *   2. Absolute https?:// URLs — fetched via network with a 15-second timeout.
 *   3. Anything else     — returns a typed error immediately.
 *
 * Never silently swallows errors — every failure path returns { error: string }.
 */

import { prisma } from "@/lib/prisma";

// IDs are generated by crypto.randomBytes(16).toString("hex") → 32 hex chars
const INTERNAL_MEDIA_RE = /^\/api\/media\/([a-f0-9]+)$/i;
const TIMEOUT_MS = 15_000;

export type ImageBufferResult =
  | { buffer: Buffer; mimeType: string }
  | { error: string };

export async function fetchImageBuffer(url: string): Promise<ImageBufferResult> {
  if (!url?.trim()) {
    return { error: "Imagem sem URL." };
  }

  // ── Path 1: internal /api/media/[id] — read directly from DB ──────────────
  const mediaMatch = url.match(INTERNAL_MEDIA_RE);
  if (mediaMatch) {
    const mediaId = mediaMatch[1]!;
    try {
      const record = await prisma.mediaUpload.findUnique({
        where:  { id: mediaId },
        select: { data: true, mimeType: true },
      });
      if (!record) {
        return { error: `Internal media not found in database: ${url}` };
      }
      return { buffer: Buffer.from(record.data), mimeType: record.mimeType };
    } catch (err) {
      return {
        error: `Failed to read internal media ${url}: ${
          err instanceof Error ? err.message : String(err)
        }`,
      };
    }
  }

  // ── Path 2: relative but not /api/media — unsupported ────────────────────
  if (url.startsWith("/")) {
    return {
      error: `Relative URL não suportada fora de /api/media/: ${url}`,
    };
  }

  // ── Path 3: absolute URL — fetch via network ──────────────────────────────
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(url);
  } catch {
    return { error: `URL inválida: ${url}` };
  }

  if (parsedUrl.protocol !== "http:" && parsedUrl.protocol !== "https:") {
    return { error: `Protocolo não suportado: ${parsedUrl.protocol}` };
  }

  const ctrl  = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(url, { signal: ctrl.signal });
    if (!res.ok) return { error: `HTTP ${res.status} fetching source image` };

    const bytes = await res.arrayBuffer();
    const mimeType = (res.headers.get("content-type") ?? "image/jpeg")
      .split(";")[0]?.trim() ?? "image/jpeg";
    return { buffer: Buffer.from(bytes), mimeType };
  } catch (err) {
    return { error: err instanceof Error ? err.message : String(err) };
  } finally {
    clearTimeout(timer);
  }
}
